library(data.table)
library(DT)
library(eurostat)
library(graphics)
library(htmltools)
library(leaflet)
library(markdown)
library(plotly)
library(RColorBrewer)
library(sf)
library(shiny)
library(shinycssloaders)
library(shinyscreenshot)
library(shinyWidgets)

sapply(list.files("www", full.names = TRUE, pattern = ".R$"), source)
