#' AMView package imports
#'
#' @name AMView
#' @importFrom bslib bs_theme
#' @importFrom data.table fread
#' @importFrom data.table is.data.table
#' @importFrom data.table merge.data.table
#' @importFrom data.table set
#' @importFrom data.table setDT
#' @importFrom data.table setnames
#' @importFrom DT datatable
#' @importFrom DT dataTableOutput
#' @importFrom DT renderDataTable
#' @importFrom htmltools htmlEscape
#' @importFrom eurostat get_eurostat_geospatial
#' @importFrom leaflet addPolygons
#' @importFrom leaflet addPolylines
#' @importFrom leaflet addTiles
#' @importFrom leaflet colorBin
#' @importFrom leaflet labelOptions
#' @importFrom leaflet leaflet
#' @importFrom leaflet leafletOptions
#' @importFrom leaflet leafletOutput
#' @importFrom leaflet leafletProxy
#' @importFrom leaflet removeShape
#' @importFrom leaflet renderLeaflet
#' @importFrom plotly layout
#' @importFrom plotly renderPlotly
#' @importFrom plotly plotlyOutput
#' @importFrom plotly plot_ly
#' @importFrom shiny br
#' @importFrom shiny column
#' @importFrom shiny downloadButton
#' @importFrom shiny downloadHandler
#' @importFrom shiny headerPanel
#' @importFrom shiny h3
#' @importFrom shiny h4
#' @importFrom shiny h5
#' @importFrom shiny radioButtons
#' @importFrom shiny icon
#' @importFrom shiny navbarPage
#' @importFrom shiny fluidRow
#' @importFrom shiny modalDialog
#' @importFrom shiny observeEvent
#' @importFrom shiny p
#' @importFrom shiny radioButtons
#' @importFrom shiny reactive
#' @importFrom shiny reactiveVal
#' @importFrom shiny renderUI
#' @importFrom shiny runApp
#' @importFrom shiny selectInput
#' @importFrom shiny shinyApp
#' @importFrom shiny showModal
#' @importFrom shiny sliderInput
#' @importFrom shiny tabPanel
#' @importFrom shiny tagList
#' @importFrom shiny tags
#' @importFrom shiny uiOutput
#' @importFrom shiny updateRadioButtons
#' @importFrom shiny wellPanel
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyscreenshot screenshotButton
#' @importFrom shinyWidgets pickerInput
#' @importFrom shinyWidgets pickerOptions
#' @importFrom shinyWidgets updatePickerInput
#' @importFrom stats runif
#' @importFrom utils write.csv
#'
NULL
